 # logger name
# logger level
# logger file
logger:
  name: python25
  level: WARNING
  file: python25.txt

excel:
  file: cases.xlsx
  sheet: login
#
#request:
#  method: post

database:
  host: '120.78.128.25'
  port: 3306
  user: 'future'
  password: '123456'
  charset: 'utf8'
  database: 'futureloan'